project:
  type: website
  output-dir: docs

website:
  title: "Personal Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: Visualisation.qmd
        text: Visualisation

format:
  html:
    theme: sandstone
    css: styles.css
    highlight-style: espresso
    toc: true

editor: visual

